---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: minecraft-dev
  namespace: minecraft
  annotations:
    flux.weave.works/automated: "true"
spec:
  releaseName: minecraft-dev
  chart:
    git: git@github.com:Docteur-RS/devopswillkillme.git
    path: charts/minecraft
    ref: master
  values:
    minecraftServer:
      eula: "TRUE"