apiVersion: apps/v1
kind: Deployment
metadata:
  name: testserverxa
  labels:
    app: deployxa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployxa
  template:
    metadata:
      labels:
        app: deployxa
    spec:
      containers:
      - name: testserverxa
        image: wingardiumleviosa/testserver:v1
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: testserverxa
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: deployxa