apiVersion: apps/v1
kind: Deployment
metadata:
  name: testserverA
  labels:
    app: deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployA
  template:
    metadata:
      labels:
        app: deployA
    spec:
      containers:
      - name: testserverA
        image: wingardiumleviosa/testserver:v1
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: testserverA
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: deployA