apiVersion: apps/v1
kind: Deployment
metadata:
  name: testserver5
  labels:
    app: deploy5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy5
  template:
    metadata:
      labels:
        app: deploy5
    spec:
      containers:
      - name: testserver5
        image: wingardiumleviosa/testserver:v1
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: testserver5
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: deploy5