apiVersion: apps/v1
kind: Deployment
metadata:
  name: testserverx
  labels:
    app: deployx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployx
  template:
    metadata:
      labels:
        app: deployx
    spec:
      containers:
      - name: testserverx
        image: wingardiumleviosa/testserver:v1
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: testserverx
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: deployx