apiVersion: apps/v1
kind: Deployment
metadata:
  name: testserver4
  labels:
    app: deploy4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy4
  template:
    metadata:
      labels:
        app: deploy4
    spec:
      containers:
      - name: testserver4
        image: wingardiumleviosa/testserver:v1
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: testserver4
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: deploy4